export default $doctype<"Work Shift">({
    name: {
        type: "Text",
        label: "Name",
        required: 1,
    },
    mon_start_time: {
        type: "Time",
        label: "Monday Start Time",
        required: 1,
        readonly_on: "doc.mon_is_day_off",
        default: "00:00:00",
    },
    mon_end_time: {
        type: "Time",
        label: "Monday End Time",
        required: 1,
        readonly_on: "doc.mon_is_day_off",
        default: "00:00:00",
    },
    mon_break_start: {
        type: "Time",
        label: "Monday Break Start",
        required: 1,
        readonly_on: "doc.mon_is_day_off",
        default: "00:00:00",
    },
    mon_break_end: {
        type: "Time",
        label: "Monday Break End",
        required: 1,
        readonly_on: "doc.mon_is_day_off",
        default: "00:00:00",
    },
    mon_is_day_off: {
        type: "Check",
        label: "Monday is Day Off",
        default: "0",
    },
    tue_start_time: {
        type: "Time",
        label: "Tuesday Start Time",
        required: 1,
        readonly_on: "doc.tue_is_day_off",
        default: "00:00:00",
    },
    tue_end_time: {
        type: "Time",
        label: "Tuesday End Time",
        required: 1,
        readonly_on: "doc.tue_is_day_off",
        default: "00:00:00",
    },
    tue_break_start: {
        type: "Time",
        label: "Tuesday Break Start",
        required: 1,
        readonly_on: "doc.tue_is_day_off",
        default: "00:00:00",
    },
    tue_break_end: {
        type: "Time",
        label: "Tuesday Break End",
        required: 1,
        readonly_on: "doc.tue_is_day_off",
        default: "00:00:00",
    },
    tue_is_day_off: {
        type: "Check",
        label: "Tuesday is Day Off",
        default: "0",
    },
    wed_start_time: {
        type: "Time",
        label: "Wednesday Start Time",
        required: 1,
        readonly_on: "doc.wed_is_day_off",
        default: "00:00:00",
    },
    wed_end_time: {
        type: "Time",
        label: "Wednesday End Time",
        required: 1,
        readonly_on: "doc.wed_is_day_off",
        default: "00:00:00",
    },
    wed_break_start: {
        type: "Time",
        label: "Wednesday Break Start",
        required: 1,
        readonly_on: "doc.wed_is_day_off",
        default: "00:00:00",
    },
    wed_break_end: {
        type: "Time",
        label: "Wednesday Break End",
        required: 1,
        readonly_on: "doc.wed_is_day_off",
        default: "00:00:00",
    },
    wed_is_day_off: {
        type: "Check",
        label: "Wednesday is Day Off",
        default: "0",
    },
    thu_start_time: {
        type: "Time",
        label: "Thursday Start Time",
        required: 1,
        readonly_on: "doc.thu_is_day_off",
        default: "00:00:00",
    },
    thu_end_time: {
        type: "Time",
        label: "Thursday End Time",
        required: 1,
        readonly_on: "doc.thu_is_day_off",
        default: "00:00:00",
    },
    thu_break_start: {
        type: "Time",
        label: "Thursday Break Start",
        required: 1,
        readonly_on: "doc.thu_is_day_off",
        default: "00:00:00",
    },
    thu_break_end: {
        type: "Time",
        label: "Thursday Break End",
        required: 1,
        readonly_on: "doc.thu_is_day_off",
        default: "00:00:00",
    },
    thu_is_day_off: {
        type: "Check",
        label: "Thursday is Day Off",
        default: "0",
    },
    fri_start_time: {
        type: "Time",
        label: "Friday Start Time",
        required: 1,
        readonly_on: "doc.fri_is_day_off",
        default: "00:00:00",
    },
    fri_end_time: {
        type: "Time",
        label: "Friday End Time",
        required: 1,
        readonly_on: "doc.fri_is_day_off",
        default: "00:00:00",
    },
    fri_break_start: {
        type: "Time",
        label: "Friday Break Start",
        required: 1,
        readonly_on: "doc.fri_is_day_off",
        default: "00:00:00",
    },
    fri_break_end: {
        type: "Time",
        label: "Friday Break End",
        required: 1,
        readonly_on: "doc.fri_is_day_off",
        default: "00:00:00",
    },
    fri_is_day_off: {
        type: "Check",
        label: "Friday is Day Off",
        default: "0",
    },
    sat_start_time: {
        type: "Time",
        label: "Saturday Start Time",
        required: 1,
        readonly_on: "doc.sat_is_day_off",
        default: "00:00:00",
    },
    sat_end_time: {
        type: "Time",
        label: "Saturday End Time",
        required: 1,
        readonly_on: "doc.sat_is_day_off",
        default: "00:00:00",
    },
    sat_break_start: {
        type: "Time",
        label: "Saturday Break Start",
        required: 1,
        readonly_on: "doc.sat_is_day_off",
        default: "00:00:00",
    },
    sat_break_end: {
        type: "Time",
        label: "Saturday Break End",
        required: 1,
        readonly_on: "doc.sat_is_day_off",
        default: "00:00:00",
    },
    sat_is_day_off: {
        type: "Check",
        label: "Saturday is Day Off",
        default: "0",
    },
    sun_start_time: {
        type: "Time",
        label: "Sunday Start Time",
        required: 1,
        readonly_on: "doc.sun_is_day_off",
        default: "00:00:00",
    },
    sun_end_time: {
        type: "Time",
        label: "Sunday End Time",
        required: 1,
        readonly_on: "doc.sun_is_day_off",
        default: "00:00:00",
    },
    sun_break_start: {
        type: "Time",
        label: "Sunday Break Start",
        required: 1,
        readonly_on: "doc.sun_is_day_off",
        default: "00:00:00",
    },
    sun_break_end: {
        type: "Time",
        label: "Sunday Break End",
        required: 1,
        readonly_on: "doc.sun_is_day_off",
        default: "00:00:00",
    },
    sun_is_day_off: {
        type: "Check",
        label: "Sunday is Day Off",
        default: "0",
    },
    can_early_entry: {
        type: "Float",
        label: "Can Early Entry (Minutes)",
        default: "0",
    },
    can_late_entry: {
        type: "Float",
        label: "Can Late Entry (Minutes)",
        default: "0",
    },
    can_early_exit: {
        type: "Float",
        label: "Can Early Exit (Minutes)",
        default: "0",
    },
    can_late_exit: {
        type: "Float",
        label: "Can Late Exit (Minutes)",
        default: "0",
    },
}, {
    label: "Work Shift",
    naming_series: "{{name}}",
    search_fields: "name",
    tabs: JSON.stringify([{
        type: "Tab",
        label: "Main",
        layout: [
            { type: "section", value: "Work Shift", align: "left" },
            [
                { type: "field", value: "name", align: "left" },
            ],
            { type: "section", value: "Days", align: "left" },
            [
                { type: "field", value: "mon_start_time", align: "left" },
                { type: "field", value: "mon_break_start", align: "left" },
                { type: "field", value: "mon_break_end", align: "left" },
                { type: "field", value: "mon_end_time", align: "left" },
                { type: "field", value: "mon_is_day_off", align: "left" },
            ],
            [
                { type: "field", value: "tue_start_time", align: "left" },
                { type: "field", value: "tue_break_start", align: "left" },
                { type: "field", value: "tue_break_end", align: "left" },
                { type: "field", value: "tue_end_time", align: "left" },
                { type: "field", value: "tue_is_day_off", align: "left" },
            ],
            [
                { type: "field", value: "wed_start_time", align: "left" },
                { type: "field", value: "wed_break_start", align: "left" },
                { type: "field", value: "wed_break_end", align: "left" },
                { type: "field", value: "wed_end_time", align: "left" },
                { type: "field", value: "wed_is_day_off", align: "left" },
            ],
            [
                { type: "field", value: "thu_start_time", align: "left" },
                { type: "field", value: "thu_break_start", align: "left" },
                { type: "field", value: "thu_break_end", align: "left" },
                { type: "field", value: "thu_end_time", align: "left" },
                { type: "field", value: "thu_is_day_off", align: "left" },
            ],
            [
                { type: "field", value: "fri_start_time", align: "left" },
                { type: "field", value: "fri_break_start", align: "left" },
                { type: "field", value: "fri_break_end", align: "left" },
                { type: "field", value: "fri_end_time", align: "left" },
                { type: "field", value: "fri_is_day_off", align: "left" },
            ],
            [
                { type: "field", value: "sat_start_time", align: "left" },
                { type: "field", value: "sat_break_start", align: "left" },
                { type: "field", value: "sat_break_end", align: "left" },
                { type: "field", value: "sat_end_time", align: "left" },
                { type: "field", value: "sat_is_day_off", align: "left" },
            ],
            [
                { type: "field", value: "sun_start_time", align: "left" },
                { type: "field", value: "sun_break_start", align: "left" },
                { type: "field", value: "sun_break_end", align: "left" },
                { type: "field", value: "sun_end_time", align: "left" },
                { type: "field", value: "sun_is_day_off", align: "left" },
            ],
            { type: "section", value: "Checkin Rules", align: "left" },
            [
                { type: "field", value: "can_early_entry", align: "left" },
                { type: "field", value: "can_late_entry", align: "left" },
            ],
            [
                { type: "field", value: "can_early_exit", align: "left" },
                { type: "field", value: "can_late_exit", align: "left" },
            ],
        ]
    }]),
})
    .on("before_save", async ({ doc }) => {

    });